modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/SentixDev/squaremarker/issues"
showAsResourcePack = false

[[mods]]
modId = "squaremarker"
version = "${version}"
displayName = "squaremarker"
displayURL = "https://github.com/SentixDev/squaremarker"
authors = "Sentix"
description = "Marker addon for squaremap"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.squaremarker]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.squaremarker]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.squaremarker]]
modId = "cloud"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.squaremarker]]
modId = "squaremap"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
