name: "build"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:

jobs:
  call-build:
    uses: "jpenilla/actions/.github/workflows/shared-ci.yml@master"
    with:
      artifacts-path: "build/libs/*.jar"
      loom: true
      jdk-version: 21
